# --- !Ups

create table "Todos" (
  "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "text" TEXT NOT NULL,
  "complete" BOOLEAN NOT NULL
);

# --- !Downs

drop table "Todos";
