sudo: required

language: scala
jdk: openjdk12

scala:
  - 2.13.0

before_install:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose -f docker-compose.test.yml up -d

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt -Dconfig.file=server/conf/testing.conf test

after_script:
  - docker-compose -f docker-compose.test.yml down

notifications:
  email:
    on_success: never
