version: '3'
services:
  webapp:
    container_name: webapp
    image: server:0.1.0-SNAPSHOT # build by sbt docker
    command: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "9000:9000"
      - "5005:5005"
    depends_on:
      - postgres
    links:
      - "postgres:database"
  postgres:
    container_name: prod_postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - prod_postgres:/var/lib/postgresql/data
volumes:
  prod_postgres:
    driver: local
