version: '2'
services:
  webapp:
    container_name: webapp
    image: server:0.1-SNAPSHOT # build by sbt docker
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    links:
      - "postgres:database"
  postgres:
    container_name: prod_postgres
    image: postgres:9
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - prod_postgres:/var/lib/postgresql/data
volumes:
  prod_postgres:
    driver: local
