version: '3'
services:
  postgres:
    container_name: test_postgres
    image: postgres:11
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
